# Generated by Django 4.2 on 2024-05-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_image', models.ImageField(upload_to='activity')),
            ],
        ),
        migrations.DeleteModel(
            name='Acivity',
        ),
    ]
