# Generated by Django 4.2 on 2024-05-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0003_category_classes_events_venues_delete_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_image', models.ImageField(upload_to='activity')),
                ('activity_ids', models.IntegerField(choices=[])),
            ],
        ),
    ]
