# Generated by Django 4.2 on 2024-05-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0004_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='classes',
            new_name='classname',
        ),
        migrations.RenameField(
            model_name='venues',
            old_name='venues',
            new_name='venuename',
        ),
    ]
