# Generated by Django 4.2 on 2024-05-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0005_delete_activity_rename_classes_classes_classname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=255)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_image', models.ImageField(upload_to='activity')),
                ('activity_ids', models.IntegerField(choices=[(1, 'clastype'), (2, 'eventtype'), (3, 'venuettype')])),
            ],
        ),
    ]
