# Generated by Django 4.2 on 2024-05-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0006_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='pricing_types',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Paid')], max_length=50, null=True),
        ),
    ]
