# Generated by Django 4.2 on 2024-05-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0007_activity_pricing_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classes_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.classes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='event_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.events'),
        ),
        migrations.AddField(
            model_name='activity',
            name='venue_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.venues'),
        ),
    ]
