# Generated by Django 4.2 on 2024-05-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0008_activity_classes_names_activity_event_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='arabic_activityname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
