# Generated by Django 4.2 on 2024-05-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0011_activity_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='mail_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
