# Generated by Django 4.2 on 2024-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0013_activity_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='prioriy',
            field=models.IntegerField(max_length=30, null=True),
        ),
    ]
