# Generated by Django 4.2 on 2024-05-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0014_activity_prioriy'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='tickt_types',
            field=models.CharField(choices=[('1', 'Slots'), ('2', 'Ticket')], max_length=255, null=True),
        ),
    ]
