# Generated by Django 4.2 on 2024-05-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0015_activity_tickt_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status_choice',
            field=models.CharField(choices=[('1', 'Published'), ('2', 'Unpublished')], max_length=255, null=True),
        ),
    ]
