# Generated by Django 4.2 on 2024-05-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0016_activity_status_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(editable=False, max_length=255, null=True),
        ),
    ]
