# Generated by Django 4.2 on 2024-05-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0017_activity_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.TimeField(null=True),
        ),
    ]
