# Generated by Django 4.2 on 2024-05-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0018_sports_classes_activity_end_date_activity_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_tags', models.CharField(max_length=255)),
            ],
        ),
    ]
