# Generated by Django 4.2 on 2024-05-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0019_activity_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sports_classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.sports_classes'),
        ),
    ]
