# Generated by Django 4.2 on 2024-05-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0020_activity_sports_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='pricing_types',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status_choice',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='tickt_types',
        ),
    ]
