# Generated by Django 4.2 on 2024-05-10 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0021_remove_activity_pricing_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='classes_names',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='event_names',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='venue_names',
        ),
    ]
