# Generated by Django 4.2 on 2024-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0022_remove_activity_classes_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='arabic_activitydescription',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
