# Generated by Django 4.2 on 2024-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0023_alter_activity_arabic_activitydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='prioriy',
            field=models.IntegerField(null=True),
        ),
    ]
