# Generated by Django 4.2 on 2024-05-10 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0024_alter_activity_prioriy'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='classes_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.classes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='event_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.events'),
        ),
        migrations.AddField(
            model_name='activity',
            name='pricing_types',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Paid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='status_choice',
            field=models.CharField(choices=[('1', 'Published'), ('2', 'Unpublished')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='tickt_types',
            field=models.CharField(choices=[('1', 'Slots'), ('2', 'Ticket')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='venue_names',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduapp.venues'),
        ),
    ]
