# Generated by Django 4.2 on 2024-05-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0025_activity_classes_names_activity_event_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='classname',
            new_name='name',
        ),
    ]
