# Generated by Django 4.2 on 2024-05-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0026_rename_classname_classes_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='eventname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='venues',
            old_name='venuename',
            new_name='name',
        ),
    ]
