# Generated by Django 5.0.1 on 2024-05-10 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0027_rename_eventname_events_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('phone_code', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('dob', models.DateField(max_length=255)),
                ('gender', models.CharField(max_length=25)),
                ('location_id', models.CharField(max_length=255)),
                ('national_status', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
