# Generated by Django 5.0.1 on 2024-05-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0028_activity_end_time_activity_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_ids',
        ),
        migrations.AddField(
            model_name='activity',
            name='capacity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='catagory',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='landmark',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='select_sports',
            field=models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Swimming', 'Swimming'), ('Volley Ball', 'Volley Ball'), ('Music', 'Music')], max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='stundent_leval',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('InterMediate', 'InterMediate'), ('Expert', 'Expert')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sports_classes',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
