# Generated by Django 5.0.1 on 2024-05-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0029_remove_activity_activity_ids_activity_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='catagory',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
