# Generated by Django 5.0.1 on 2024-05-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0030_rename_catagory_activity_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='category',
            new_name='catagory',
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
