# Generated by Django 5.0.1 on 2024-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0031_rename_category_activity_catagory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.DateField(null=True),
        ),
    ]
