# Generated by Django 5.0.1 on 2024-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0033_alter_activity_end_time_alter_activity_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
