# Generated by Django 5.0.4 on 2024-05-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0034_alter_activity_end_time_alter_activity_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
